var iconData = {
    'iconData1': {
        'styleguide': true,
        'icons': [{
            'icon': 'icon-solid-bell',
            'label': true
        }, {
            'icon': 'icon-naked-bell',
            'label': true
        }, {
            'icon': 'icon-solid-bubbles',
            'label': true
        }, {
            'icon': 'icon-naked-bubbles',
            'label': true
        }, {
            'icon': 'icon-solid-user',
            'label': true
        }, {
            'icon': 'icon-naked-user',
            'label': true
        }, {
            'icon': 'icon-solid-menu',
            'label': true
        }]
    },
    'iconData2': {
        'styleguide': true,
        'icons': [{
            'icon': 'icon-system-menu',
            'label': true
        }, {
            'icon': 'icon-system-refresh',
            'label': true
        }, {
            'icon': 'icon-system-down-open',
            'label': true
        }, {
            'icon': 'icon-system-up-open',
            'label': true
        }, {
            'icon': 'icon-system-close',
            'label': true
        }, {
            'icon': 'icon-solid-magnifier',
            'label': true
        }, {
            'icon': 'icon-naked-magnifier',
            'label': true
        }]
    },
    'iconData3': {
        'styleguide': true,
        'icons': [{
            'icon': 'icon-solid-bubble',
            'label': true
        }, {
            'icon': 'icon-naked-bubble',
            'label': true
        }, {
            'icon': 'icon-solid-like',
            'label': true
        }, {
            'icon': 'icon-naked-like',
            'label': true
        }, {
            'icon': 'icon-solid-add',
            'label': true
        }, {
            'icon': 'icon-naked-add',
            'label': true
        }, {
            'icon': 'icon-solid-settings',
            'label': true
        }, {
            'icon': 'icon-naked-settings',
            'label': true
        }, {
            'icon': 'icon-solid-flag',
            'label': true
        }, {
            'icon': 'icon-solid-fire',
            'label': true
        }, {
            'icon': 'icon-solid-cup',
            'label': true
        }, {
            'icon': 'icon-naked-cup',
            'label': true
        }, {
            'icon': 'icon-user-arrow-left',
            'label': true
        }, {
            'icon': 'icon-user-arrow-right',
            'label': true
        }, {
            'icon': 'icon-user-star-big',
            'label': true
        }, {
            'icon': 'icon-user-star-small',
            'label': true
        }, {
            'icon': 'icon-user-check',
            'label': true
        }, {
            'icon': 'icon-user-award',
            'label': true
        }, {
            'icon': 'icon-user-star-flag',
            'label': true
        }, {
            'icon': 'icon-user-megaphone',
            'label': true
        }, {
            'icon': 'icon-user-github',
            'label': true
        }, {
            'icon': 'icon-user-linkedin',
            'label': true
        }, {
            'icon': 'icon-user-googleplus',
            'label': true
        }, {
            'icon': 'icon-user-pinterest',
            'label': true
        }, {
            'icon': 'icon-user-twitter',
            'label': true
        }, {
            'icon': 'icon-user-facebook',
            'label': true
        }, {
            'icon': 'icon-user-instagram',
            'label': true
        }, {
            'icon': 'icon-user-skype',
            'label': true
        }, {
            'icon': 'icon-user-key',
            'label': true
        }, {
            'icon': 'icon-user-url',
            'label': true
        }, {
            'icon': 'icon-user-help',
            'label': true
        }, {
            'icon': 'icon-user-mail',
            'label': true
        }, {
            'icon': 'icon-user-phone',
            'label': true
        }, {
            'icon': 'icon-user-school',
            'label': true
        }, {
            'icon': 'icon-user-clock',
            'label': true
        }, {
            'icon': 'icon-user-location',
            'label': true
        }, {
            'icon': 'icon-user-compass',
            'label': true
        }, {
            'icon': 'icon-user-map',
            'label': true
        }, {
            'icon': 'icon-user-mobile',
            'label': true
        }, {
            'icon': 'icon-user-monitor',
            'label': true
        }, {
            'icon': 'icon-user-suitcase',
            'label': true
        }, {
            'icon': 'icon-user-calendar',
            'label': true
        }, {
            'icon': 'icon-user-location-2',
            'label': true
        }, {
            'icon': 'icon-user-user',
            'label': true
        }]
    }
};
